import { Afacad_Flux } from "next/font/google";
import "./globals.css";
import TopBar from "@/components/TopBar";
import { Toaster } from "@/components/ui/toaster"
import { BusinessNameContext } from "@/context/BusinessNameContext";

const Afacad = Afacad_Flux({
  subsets: ["latin"],
  weights: ["400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${Afacad.className}`}>
        <BusinessNameContext>
        <TopBar />
        <Toaster />
        {children}
        </BusinessNameContext>
      </body>
    </html>
  );
}
